### ISSUE TITLE
Grass rendering/coloring doesn't seem to funtion correctly

### ISSUE THREAD

**Issue by zndrmn** [granny/Pl3xMap-test#63]
None of these blocks render on the map at all, and sometimes it'll render with just a default dark green color.
`Minecraft 1.21.1`
`Pl3xMap-1.21.1-508`

I know you don't do backports for updates but it would be very cool if you did for this small issue 

![image](https://github.com/user-attachments/assets/0ff1d0ff-f128-46a1-b0d3-b57f4039e0ce)

Here's part of my config:

`config.yml`
```yml
world-settings:
  default:
    # Enables this world to be rendered on the map.
    enabled: true
    render:
      # Renderers to use. Each renderer will render a different
      # type of map. The built-in renderers include:
      # vintage_story, basic, biomes, flowermap, inhabited, night, nether_roof, and vanilla
      renderers:
        basic: overworld_basic
        biomes: overworld_biomes
        inhabited: inhabited
        nether_roof: nether_roof
      # World skylight value. This is used for the day/night cycle
      # map (not yet implemented) .Values are clamped to 0-15
      # with 0 being darkest and 15 being full bright.
      skylight: 15
      # Enables blending of biome grass/foliage/water colors similar to
      # the client's biome blending option.
      # Values are clamped to 0-7
      biome-blend: 3
      # Enable translucent fluids.
      # This will make the fluids look fancier and translucent,
      # so you can see the blocks below in shallow fluids.
      translucent-fluids: false
      # Enable translucent glass.
      # This will make the glass look fancier and translucent,
      # so you can see the blocks below.
      translucent-glass: true
      # Type of heightmap to render.
      # NONE has no heightmap drawn.
      # EVEN_ODD makes every other Y layer darker, like Dynmap.
      # HIGH_CONTRAST same as MODERN, but darker.
      # LOW_CONTRAST same as MODERN, but lighter.
      # MODERN is a clearer, more detailed view.
      # OLD_SCHOOL is the old type from v1.
      # VANILLA matches the in-game vanilla maps.
      # EVEN_ODD_HIGH_CONTRAST mix of EVEN_ODD and HIGH_CONTRAST.
      # EVEN_ODD_LOW_CONTRAST mix of EVEN_ODD and LOW_CONTRAST.
      # EVEN_ODD_MODERN mix of EVEN_ODD and MODERN.
      # EVEN_ODD_OLD_SCHOOL mix of EVEN_ODD and OLD_SCHOOL.
      # EVEN_ODD_VANILLA mix of EVEN_ODD and VANILLA.
      heightmap-type: VANILLA
```
`colors.yml`
```yml
  grass:
    - minecraft:fern
    - minecraft:grass
    - minecraft:short_grass
    - minecraft:grass_block
    - minecraft:large_fern
    - minecraft:potted_fern
    - minecraft:tall_grass
```
