### ISSUE TITLE
[Bug] Map center doesn't account for The Nether or The End

### ISSUE THREAD

**Issue by zndrmn** [granny/Pl3xMap-test#65]
If the Overworld spawn location were to be set to `x: 8000`, `z: 8000`, then The Nether's center/default map location would also be at `x: 8000`, `z: 8000` instead of being at `x: 1000` `z: 1000` because of how nether travel works.

This also affects The End dimension. Instead of being near the spawn island/platform (`x: ~0`, `z: ~0`) it'll just be at `x: 8000`, `z: 8000` as well.

I think it would be best if the center/default map location could be configurable per dimension instead of using a global center

**Comment by granny** [comment]
Is this not already configurable through the `world-settings.<world>.center.x` and `world-settings.<world>.center.y` options?

```yaml
    center:
      # The x coordinate for the map to load at.
      # A value of -1 will default to world spawn.
      x: -1
      # The z coordinate for the map to load at.
      # A value of -1 will default to world spawn.
      z: -1
```
